### ISSUE TITLE
Merge the demo app with the main package

### ISSUE THREAD

**Issue by skateman** [brumik/react-wooden-tree#26]
Having a separate package for the demo app is inconsistent with all the other stuff we see in the npm/JS world. I suggest you put the demo codebase into a `src/demo` folder, put it into `.npmignore` and have the `yarn start` command serve the demo from the main package. All the extra dependencies can go as development ones.

**Comment by brumik** [comment]
@karelhala @Hyperkid123 I need a little help, I tried to merge the package.json for the demo app with the main package, but the demo app does not build and moreover I am unable to run it on a dev server. I was able to update the webpack deps to the latest version, but I am stuck with the config.

WIP: [react-wooden-tree/tree/pipelineUpdate](https://github.com/brumik/react-wooden-tree/tree/pipelineUpdate)

**Comment by Hyperkid123** [comment]
@brumik do you have some error log?

**Comment by brumik** [comment]
There is no error (it was painful to this level), just an incorrect config I think. If I run start I got this:
![Screenshot from 2019-05-06 10-32-39](https://user-images.githubusercontent.com/8531681/57211844-6f30a480-6fea-11e9-9c16-bdae78837a9f.png)

**Comment by Hyperkid123** [comment]
Ah i think you need to set entry point for dev server. Now you only serve the content of your root directory. You should set it for demo-app/index.html (or where your index for demo is). This should help: https://webpack.js.org/configuration/dev-server/

**Comment by brumik** [comment]
Do I have to build it before serving right? How do I do it?

**Comment by Hyperkid123** [comment]
I think so. There would be also another option. Moving the demo to `/src` and import the components from their source files. Then it would be hot reloading automatically

**Comment by brumik** [comment]
I tried to define the demo app as a new entry point to compile but I bumped into this:
```
ERROR in ./demo-app/src/index.tsx 12:4
Module parse failed: Unexpected token (12:4)
You may need an appropriate loader to handle this file type.
```

I thought that the loaders working with all entry points same.

**Comment by Hyperkid123** [comment]
@brumik check your gitter :wink:
