### ISSUE TITLE
Exposing params or methods for CSS generation

### ISSUE THREAD

**Issue by brumik** [brumik/react-wooden-tree#49]
@himdel

I think it could be possible to accept a `generateCss` function in the params. If it is not supplied the original one would be used and adding a helper method to get the tree depth. 

Or/And maybe I could add a function to return the generated CSS as a string, so the parent component could decide where to put it, or if multiple trees are on the page merge them. 

What do you think?

**Comment by himdel** [comment]
Ooh, that sounds like a great idea.

I *think* overriding `generateCss` sounds better if you want to keep wooden tree working (indented) out of the box.

But OTOH I'd also be OK with just documenting what we need to do, so both work.

**Comment by brumik** [comment]
I meant override as well. I add this feature to my todo list.
